"use client"

import { useState } from "react";
import SideBar from "@/components/sideBar/SideBar";
import './globals.css';

export const metadata = {
  title: 'dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [open, setOpen] = useState(false);

  return (
    <html lang="en">
      <body className={`relative grid grid-rows-1 font-Montserrat transition duration-700 overflow-x-hidden`}
      style={{ gridTemplateColumns: open ? '270px 1fr' : '60px 1fr' }} >
        <SideBar open={open} setOpen={setOpen} />
        {children}
      </body>
    </html>
  )
}