"use client"

import { useState } from "react";
import SideBar from "@/components/sideBar/SideBar";
import SearchBar from '@/components/sideBar/SearchBar'
import './globals.css';

export const metadata = {
  title: 'dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [open, setOpen] = useState(false);

  return (
    <html lang="en">
      <body className={`relative grid grid-cols-1 ${open ? "md:grid-cols-open" : "md:grid-cols-close"} grid-rows-1 font-Poppins transition duration-700 overflow-x-hidden`}
       >
        <SearchBar open={open} setOpen={setOpen} />
        <SideBar open={open} setOpen={setOpen} />
        {children}
      </body>
    </html>
  )
}